### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by dannymell** [matthew-pye/Backyard-Monsters#1]
please tell me how to install

**Comment by matthew-pye** [comment]
Sorry, there is nothing to install this was a project to remake backyard monsters, but I haven't had time to start on this project yet

**Comment by dannymell** [comment]
> ut I haven't had time to start on this

aww okie 
it was an amazinggggg game you got any sever data of it?

**Comment by matthew-pye** [comment]
I don't have any files for it really any I do have where pulled from the Wiki; I went looking for the game a couple months ago, most of the forums I searched were people looking for the game also with it being a Facebook game no one seems to have a backup of it. The closest I got was some mobile version of the game, but all the links were dead for it, and it was apple only.

**Comment by dannymell** [comment]
> osest I got was some mobile version of the game, but all the links were dead for it, and it was apple only.

we all in the same boat

**Comment by matthew-pye** [comment]
I'll keep my eyes peeled and post a link here if ever get a lead.

**Comment by dannymell** [comment]
t

> I'll keep my eyes peeled and post a link here if ever get a lead.

tysm
